<%@ Page Title="" Language="C#" MasterPageFile="~/Principal.Master" AutoEventWireup="true" CodeBehind="MostrarUsuarios.aspx.cs" Inherits="MedidoresGR2.MostrarUsuarios" %>
<asp:Content ID="Content1" ContentPlaceHolderID="Contenido" runat="server">
    <div class="row mt-5">
       <asp:GridView ID="grillaUsuarios" OnRowEditing="grillaUsuarios_RowEditing" OnRowDeleting="grillaUsuarios_RowDeleting" AutoGenerateDeleteButton="true" AutoGenerateEditButton="true" AutoGenerateColumns="false" ShowHeaderWhenEmpty="true" CssClass="table table-hover table-bordered" EmptyDataText="No hay Registros" runat="server" DataKeyNames="idUsuario">
            <Columns>
                <asp:BoundField HeaderText="Id" DataField="idUsuario" />
                <asp:BoundField HeaderText="Rut" DataField="rut" />
                <asp:BoundField HeaderText="Nombre" DataField="nombre" />
                <asp:BoundField HeaderText="Correo" DataField="correoElectronico" />
                <asp:BoundField HeaderText="Contraseña" DataField="contrasena" />

            </Columns>
        </asp:GridView>

    </div>
</asp:Content>
